"""
@author axiner
@version v1.0.0
@created 2021/12/12 13:14
@abstract
@description
@history
"""


class Versions:
    ALL = [
        ('1.6.9', 'add@包刷新等'),
        ('1.6.8', 'opt@utils等优化'),
        ('1.6.7', 'chg@utils&log'),
        ('1.6.6', 'chg@相关优化&新增转为异步函数装饰器'),
        ('1.6.5', 'chg@pytcli.set_mirrors'),
        ('1.6.4', 'add@docker.yaml.zincsearch'),
        ('1.6.3', 'chg@docker.yaml'),
        ('1.6.2', 'chg@log&pytcli'),
        ('1.6.1', 'opt@codec&log'),
        ('1.6.0', 'opt@调优'),
        ('1.5.9', 'chg@pytcli'),
        ('1.5.8', 'chg@调优相关'),
        ('1.5.7', 'opt@优化相关'),
        ('1.5.6', 'chg@删除无用代码'),
        ('1.5.5', 'chg@增加及修复相关'),
        ('1.5.4', 'opt@autodriver'),
        ('1.5.3', 'chg@pytcli.docker'),
        ('1.5.2', 'opt@优化代码'),
        ('1.5.1', 'chg@pytcli'),
        ('1.5.0', 'fix@autodriver'),
        ('1.4.9', 'chg@pytcli'),
        ('1.4.8', 'add@新增雪花服务等'),
        ('1.4.7', 'chg@crypto->cipher'),
        ('1.4.6', 'chg@调整文档等'),
        ('1.4.5', 'add@pytcli.tmpl2bash'),
        ('1.4.4', 'chg@重整'),
        ('1.4.3', 'add@pytcli.docker'),
        ('1.4.2', 'opt@pytcli.set-conda'),
        ('1.4.1', 'opt@pytcli参数调优'),
        ('1.4.0', 'opt@pytcli.set-mirrors'),
        ('1.3.9', 'opt@系统名称校验&文档'),
        ('1.3.8', 'chg@docker.set-daemon'),
        ('1.3.7', 'chg@docker服务'),
        ('1.3.6', 'chg@CRLF转换为LF'),
        ('1.3.5', 'chg@命令行脚本权限&参数校验&错误提示'),
        ('1.3.4', 'chg@系统校验问题'),
        ('1.3.3', 'chg@相关命令行'),
        ('1.3.2', 'add@docker相关命令'),
        ('1.3.1', 'opt@优化代码'),
        ('1.3.0', 'chg@修改注释'),
        ('1.2.9', 'chg@修改注释'),
        ('1.2.8', 'opt@py2pyd&优化其他'),
        ('1.2.7', 'chg@增加py2pyd&调整tcli&优化代码'),
        ('1.2.6', 'add@重定向标准输出错误到null'),
        ('1.2.5', 'opt@guid'),
        ('1.2.4', 'opt@redis唯一id'),
        ('1.2.3', 'chg@新增全局唯一id&修改锁'),
        ('1.2.2', 'fix@锁问题'),
        ('1.2.1', 'opt@锁变量名'),
        ('1.2.0', 'fix@锁参数问题'),
        ('1.1.9', 'fix@锁释放问题'),
        ('1.1.8', 'opt@锁配置'),
        ('1.1.7', 'add@锁&redis连接池'),
        ('1.1.6', 'opt@雪花算法'),
        ('1.1.5', 'chg@雪花算法配置'),
        ('1.1.4', 'fix@自动下载驱动mac环境问题'),
        ('1.1.3', 'chg@雪花算法配置'),
        ('1.1.2', 'add@日志模块&雪花算法'),
        ('1.1.1', 'chg@驱动自动下载命令路径空格及打印问题&pip源配置'),
        ('1.1.0', 'add@...'),
        ('1.0.0', 'init@...'),
    ]
